In [2]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [3]:
import os
import numpy as np
import pandas as pd

In [4]:
import gdown
import optuna
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_absolute_percentage_error as mape
from xgboost import XGBRegressor

tscv = TimeSeriesSplit(n_splits=3)

In [23]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
datafile_dict={
    "train_transformed_data.csv": "1w_ZOLTTc8WnLj7l8bnwo8Vuz1ii_ZBTY"
    ,"validate_transformed_data.csv" : "1SI5pS8igjgATw5fSPB8hYt5vc62aiVHF"
    ,"test_data.csv" : "1JhzqIAupBjD-vZTqnaAqL1OI9HIpD9O6"
}
#remove existing files
for filename in datafile_dict.keys():
    if os.path.exists(filename):
        os.remove(filename)
        print(f"Removed {filename}")
    else:
        print(f"{filename} not found, skipping removal.")
#doanload new files from drive
for filename, file_id in datafile_dict.items():
  gdown.download(id=file_id, output=filename, quiet=False)

train_transformed_data.csv not found, skipping removal.
validate_transformed_data.csv not found, skipping removal.
test_data.csv not found, skipping removal.

Downloading...
From: https://drive.google.com/uc?id=1w_ZOLTTc8WnLj7l8bnwo8Vuz1ii_ZBTY
To: /content/train_transformed_data.csv
100%|██████████| 28.5M/28.5M [00:00<00:00, 191MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SI5pS8igjgATw5fSPB8hYt5vc62aiVHF
To: /content/validate_transformed_data.csv
100%|██████████| 6.29M/6.29M [00:00<00:00, 213MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JhzqIAupBjD-vZTqnaAqL1OI9HIpD9O6
To: /content/test_data.csv
100%|██████████| 572k/572k [00:00<00:00, 66.4MB/s]

In [6]:
def load_data_dat(filename):
  if filename.endswith('.csv'):
    df=pd.read_csv(filename)
  return df

train_df= load_data_dat('train_transformed_data.csv')
val_df= load_data_dat('validate_transformed_data.csv')
test_df= load_data_dat('test_data.csv')

In [36]:
FEATURES = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_aov',
    'Sales','#Order'
]
FEATURES_ORDERS = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_aov'
]

FEATURES_SALES = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_aov','pred_orders'
]

column_dtype_map_dict = {'Store_id': 'int64',
 'Store_Type_S1': 'int64',
 'Store_Type_S2': 'int64',
 'Store_Type_S3': 'int64',
 'Store_Type_S4': 'int64',
 'Location_Type_L1': 'int64',
 'Location_Type_L2': 'int64',
 'Location_Type_L3': 'int64',
 'Location_Type_L4': 'int64',
 'Location_Type_L5': 'int64',
 'Region_Code_R1': 'int64',
 'Region_Code_R2': 'int64',
 'Region_Code_R3': 'int64',
 'Region_Code_R4': 'int64',
 'Discount_Flag': 'int64',
 'Holiday': 'int64',
 'day': 'int64',
 'month': 'int64',
 'weekday': 'int64',
 'weekofyear': 'int64',
 'is_weekend': 'int64',
 'lag_1_#Order': 'float64',
 'lag_7_#Order': 'float64',
 'rolling_#Order_7': 'float64',
 'lag_1_Sales': 'float64',
 'lag_7_Sales': 'float64',
 'rolling_Sales_7': 'float64',
 'lag_1_aov': 'float64',
 'Sales': 'float64',
 '#Order': 'float64',
 'pred_orders': 'float64'}

In [8]:
train_df['Date'] = pd.to_datetime(train_df['Date'])
val_df['Date'] = pd.to_datetime(val_df['Date'])
train_df = train_df.sort_values("Date")
val_df = val_df.sort_values("Date")
train_df=train_df[FEATURES]
val_df=val_df[FEATURES]

In [ ]:
def format_df_dtype(df, features_dtype_map_dict):
    for col, dtype in features_dtype_map_dict.items():
        if col in df.columns:
            df[col] = df[col].astype(dtype)
    return df

train_df = format_df_dtype(train_df, column_dtype_map_dict)
val_df = format_df_dtype(val_df, column_dtype_map_dict)

#**XGBoost**
---

##**1. Orders**
---

In [10]:
TARGET = "#Order"  # or "#Order"

X = train_df[FEATURES_ORDERS]
y = train_df[TARGET]

In [34]:
def wape(y_true, y_pred):
    return np.sum(np.abs(y_true - y_pred)) / (np.sum(y_true) + 1e-8)

In [12]:
tscv = TimeSeriesSplit(n_splits=3)
mean_metric_scores = []
def objective(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 700),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "subsample": trial.suggest_float("subsample", 0.7, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.7, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0, 5),
        "reg_lambda": trial.suggest_float("reg_lambda", 0, 5),
        "random_state": 42,
        "n_jobs": -1
    }

    wape_scores = []
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    mape_scores = []

    for train_idx, val_idx in tscv.split(X):

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        model = XGBRegressor(**params)
        model.fit(X_train_fold, y_train_fold)

        preds = model.predict(X_val_fold)
        #score = mean_absolute_error(y_val_fold, preds)
        #score = wape(y_val_fold, preds)

        wape_scores.append(wape(y_val_fold, preds))
        mae_scores.append(mean_absolute_error(y_val_fold, preds))
        mse_scores.append(mean_squared_error(y_val_fold, preds))
        rmse_scores.append(np.sqrt(mean_squared_error(y_val_fold, preds)))
        mape_scores.append(mape(y_val_fold, preds))

    average_metric = np.mean(mae_scores)
    mean_score = mean_metric_scores.append((np.mean(wape_scores),np.mean(mae_scores),np.mean(mse_scores),np.mean(rmse_scores),np.mean(mape_scores),params))
    return average_metric

In [13]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Score:", study.best_value)

[I 2026-04-20 18:05:31,674] A new study created in memory with name: no-name-878db11a-c49c-4e0a-9e44-0473ca5e19fe
[I 2026-04-20 18:05:56,304] Trial 0 finished with value: 12.333151021093235 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.196505756458993, 'subsample': 0.7448895473837225, 'colsample_bytree': 0.7219594126069286, 'reg_alpha': 1.7876816309995114, 'reg_lambda': 0.07652898135667441}. Best is trial 0 with value: 12.333151021093235.
[I 2026-04-20 18:06:08,956] Trial 1 finished with value: 12.370100433156418 and parameters: {'n_estimators': 429, 'max_depth': 6, 'learning_rate': 0.18502235924882532, 'subsample': 0.9890994376807555, 'colsample_bytree': 0.7390206721266279, 'reg_alpha': 2.1421400969567266, 'reg_lambda': 0.8734985955192764}. Best is trial 0 with value: 12.333151021093235.
[I 2026-04-20 18:06:17,913] Trial 2 finished with value: 10.682246805124796 and parameters: {'n_estimators': 291, 'max_depth': 5, 'learning_rate': 0.03753191926462513, 'subsample': 0.7361284557647968, 'colsample_bytree': 0.7707718398065945, 'reg_alpha': 1.8038584307339112, 'reg_lambda': 4.39362322181664}. Best is trial 2 with value: 10.682246805124796.
[I 2026-04-20 18:06:28,817] Trial 3 finished with value: 11.811471230541338 and parameters: {'n_estimators': 327, 'max_depth': 6, 'learning_rate': 0.1360254278326659, 'subsample': 0.8034540887023918, 'colsample_bytree': 0.8291666374097475, 'reg_alpha': 3.7194045008673675, 'reg_lambda': 0.7331467763513272}. Best is trial 2 with value: 10.682246805124796.
[I 2026-04-20 18:06:36,771] Trial 4 finished with value: 11.04189430788585 and parameters: {'n_estimators': 424, 'max_depth': 4, 'learning_rate': 0.06452212221297003, 'subsample': 0.8594327460748287, 'colsample_bytree': 0.7217950718452659, 'reg_alpha': 0.9697380700465669, 'reg_lambda': 1.2675915803999533}. Best is trial 2 with value: 10.682246805124796.
[I 2026-04-20 18:06:53,768] Trial 5 finished with value: 10.601300630401868 and parameters: {'n_estimators': 225, 'max_depth': 8, 'learning_rate': 0.017260970343637827, 'subsample': 0.9106202216595758, 'colsample_bytree': 0.9666139474606861, 'reg_alpha': 0.2341138448189889, 'reg_lambda': 0.6837331819699105}. Best is trial 5 with value: 10.601300630401868.
[I 2026-04-20 18:07:00,356] Trial 6 finished with value: 11.6989489910507 and parameters: {'n_estimators': 343, 'max_depth': 4, 'learning_rate': 0.14866778654604987, 'subsample': 0.7645404759597957, 'colsample_bytree': 0.9525806516571498, 'reg_alpha': 0.08233807460464648, 'reg_lambda': 3.80281472971551}. Best is trial 5 with value: 10.601300630401868.
[I 2026-04-20 18:07:22,529] Trial 7 finished with value: 11.89248802861925 and parameters: {'n_estimators': 428, 'max_depth': 8, 'learning_rate': 0.1375863831012669, 'subsample': 0.9545794485748809, 'colsample_bytree': 0.8080061448342089, 'reg_alpha': 3.4451276355236886, 'reg_lambda': 0.5374518493912117}. Best is trial 5 with value: 10.601300630401868.
[I 2026-04-20 18:07:38,349] Trial 8 finished with value: 12.048521223864833 and parameters: {'n_estimators': 519, 'max_depth': 6, 'learning_rate': 0.16098820531243455, 'subsample': 0.8429621465019632, 'colsample_bytree': 0.8431394241090111, 'reg_alpha': 2.92151893874734, 'reg_lambda': 2.5185875489337093}. Best is trial 5 with value: 10.601300630401868.
[I 2026-04-20 18:08:09,333] Trial 9 finished with value: 11.4821872331401 and parameters: {'n_estimators': 592, 'max_depth': 8, 'learning_rate': 0.061260525077074704, 'subsample': 0.8993195346427022, 'colsample_bytree': 0.8116733286790978, 'reg_alpha': 3.4934567499441282, 'reg_lambda': 0.9073008526397297}. Best is trial 5 with value: 10.601300630401868.
[I 2026-04-20 18:08:38,117] Trial 10 finished with value: 10.50514863683126 and parameters: {'n_estimators': 201, 'max_depth': 10, 'learning_rate': 0.014510844047880092, 'subsample': 0.917395684507345, 'colsample_bytree': 0.993056474045261, 'reg_alpha': 4.70376720897306, 'reg_lambda': 2.241611112220969}. Best is trial 10 with value: 10.50514863683126.
[I 2026-04-20 18:09:11,210] Trial 11 finished with value: 10.63248792728987 and parameters: {'n_estimators': 218, 'max_depth': 10, 'learning_rate': 0.011059309470639602, 'subsample': 0.9155281782150704, 'colsample_bytree': 0.9982553476554835, 'reg_alpha': 4.779124929344538, 'reg_lambda': 2.100675024233318}. Best is trial 10 with value: 10.50514863683126.
[I 2026-04-20 18:09:38,845] Trial 12 finished with value: 10.458481578845378 and parameters: {'n_estimators': 201, 'max_depth': 10, 'learning_rate': 0.013960663099383598, 'subsample': 0.9208699091164867, 'colsample_bytree': 0.9170140235850499, 'reg_alpha': 4.824825650018285, 'reg_lambda': 2.4528319109319674}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:10:01,029] Trial 13 finished with value: 10.98549503352632 and parameters: {'n_estimators': 207, 'max_depth': 10, 'learning_rate': 0.09221771717466021, 'subsample': 0.9967195838776026, 'colsample_bytree': 0.9065055826822538, 'reg_alpha': 4.953879542326458, 'reg_lambda': 2.9072253830967294}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:11:13,481] Trial 14 finished with value: 10.950437637145413 and parameters: {'n_estimators': 688, 'max_depth': 10, 'learning_rate': 0.04648540409519406, 'subsample': 0.9404961037337013, 'colsample_bytree': 0.8989299898891036, 'reg_alpha': 4.258193286091584, 'reg_lambda': 1.8688727110876144}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:11:35,537] Trial 15 finished with value: 10.880613688578942 and parameters: {'n_estimators': 274, 'max_depth': 9, 'learning_rate': 0.08982770663382317, 'subsample': 0.8655301631103972, 'colsample_bytree': 0.8989343247728865, 'reg_alpha': 4.25654555479235, 'reg_lambda': 3.3400319265395937}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:12:00,822] Trial 16 finished with value: 10.8568296232092 and parameters: {'n_estimators': 284, 'max_depth': 9, 'learning_rate': 0.03352320514795424, 'subsample': 0.9547345442215301, 'colsample_bytree': 0.9422219860286387, 'reg_alpha': 4.314336132713347, 'reg_lambda': 1.71127254802287}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:12:23,305] Trial 17 finished with value: 11.714836227519394 and parameters: {'n_estimators': 501, 'max_depth': 7, 'learning_rate': 0.07138622086711945, 'subsample': 0.8172247535544894, 'colsample_bytree': 0.9968473434489713, 'reg_alpha': 2.7170329489011884, 'reg_lambda': 2.835195073417164}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:12:29,719] Trial 18 finished with value: 11.291622691825054 and parameters: {'n_estimators': 379, 'max_depth': 3, 'learning_rate': 0.11537722058074353, 'subsample': 0.8895765186920221, 'colsample_bytree': 0.8752453482539209, 'reg_alpha': 4.59258149887946, 'reg_lambda': 3.5054852351382015}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:12:41,910] Trial 19 finished with value: 10.62450226199214 and parameters: {'n_estimators': 252, 'max_depth': 7, 'learning_rate': 0.02515393399928946, 'subsample': 0.9397445245316665, 'colsample_bytree': 0.9286371689571471, 'reg_alpha': 3.4964613240352334, 'reg_lambda': 4.285343112229153}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:13:30,880] Trial 20 finished with value: 11.120577609258069 and parameters: {'n_estimators': 626, 'max_depth': 9, 'learning_rate': 0.05330885202644451, 'subsample': 0.7011378377804235, 'colsample_bytree': 0.9721076949899, 'reg_alpha': 3.998032951350486, 'reg_lambda': 4.822065917549207}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:13:47,680] Trial 21 finished with value: 10.665906979779159 and parameters: {'n_estimators': 209, 'max_depth': 8, 'learning_rate': 0.010788396418882807, 'subsample': 0.9124571242039535, 'colsample_bytree': 0.9690632882191106, 'reg_alpha': 0.4078683955160787, 'reg_lambda': 1.3981465042526353}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:14:18,680] Trial 22 finished with value: 10.609021145085293 and parameters: {'n_estimators': 248, 'max_depth': 10, 'learning_rate': 0.0250648959578929, 'subsample': 0.8863569338140618, 'colsample_bytree': 0.9240259393130701, 'reg_alpha': 0.7046429995487303, 'reg_lambda': 2.071272872382552}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:14:41,447] Trial 23 finished with value: 10.675597630380226 and parameters: {'n_estimators': 310, 'max_depth': 8, 'learning_rate': 0.011925000239345672, 'subsample': 0.9264921559283982, 'colsample_bytree': 0.9698695959694864, 'reg_alpha': 2.9141047422304576, 'reg_lambda': 0.023697679169451646}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:14:56,991] Trial 24 finished with value: 10.914698241767693 and parameters: {'n_estimators': 201, 'max_depth': 9, 'learning_rate': 0.07685824070052587, 'subsample': 0.9797237458441552, 'colsample_bytree': 0.8656771450244548, 'reg_alpha': 1.0125788806554283, 'reg_lambda': 2.3730880203013434}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:15:27,913] Trial 25 finished with value: 10.760307456595802 and parameters: {'n_estimators': 248, 'max_depth': 10, 'learning_rate': 0.0410074313166884, 'subsample': 0.8808657265492653, 'colsample_bytree': 0.9526879369194864, 'reg_alpha': 1.2655600261974325, 'reg_lambda': 2.9423965453732466}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:15:40,327] Trial 26 finished with value: 10.804610397052427 and parameters: {'n_estimators': 242, 'max_depth': 7, 'learning_rate': 0.0247232807250731, 'subsample': 0.9698504333116194, 'colsample_bytree': 0.9888836287937289, 'reg_alpha': 2.241928415626242, 'reg_lambda': 1.430844853175334}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:16:09,317] Trial 27 finished with value: 10.853856400839547 and parameters: {'n_estimators': 363, 'max_depth': 9, 'learning_rate': 0.05145886384614054, 'subsample': 0.8406435191015056, 'colsample_bytree': 0.922192987372785, 'reg_alpha': 3.1539312217968654, 'reg_lambda': 2.5028928020547583}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:16:58,954] Trial 28 finished with value: 10.77065900553032 and parameters: {'n_estimators': 387, 'max_depth': 10, 'learning_rate': 0.02305815318551485, 'subsample': 0.9139216010572588, 'colsample_bytree': 0.8771814895673319, 'reg_alpha': 4.535200996734907, 'reg_lambda': 0.34177114166981637}. Best is trial 12 with value: 10.458481578845378.
[I 2026-04-20 18:17:18,003] Trial 29 finished with value: 11.566351964479113 and parameters: {'n_estimators': 312, 'max_depth': 8, 'learning_rate': 0.11118667508264918, 'subsample': 0.8199618455457488, 'colsample_bytree': 0.9748388542426143, 'reg_alpha': 1.66799891271644, 'reg_lambda': 1.0945610168104065}. Best is trial 12 with value: 10.458481578845378.

Best Params: {'n_estimators': 201, 'max_depth': 10, 'learning_rate': 0.013960663099383598, 'subsample': 0.9208699091164867, 'colsample_bytree': 0.9170140235850499, 'reg_alpha': 4.824825650018285, 'reg_lambda': 2.4528319109319674}
Best Score: 10.458481578845378

In [15]:
formatted_data = []
for wape, mae, mse, rmse, mape, params in mean_metric_scores:
    # Combine metrics and the params dictionary into one flat dict
    row = {
        'WAPE': wape, 'MAE': mae, 'MSE': mse, 
        'RMSE': rmse, 'MAPE': mape
    }
    row.update(params)
    formatted_data.append(row)

df = pd.DataFrame(formatted_data)
df

,WAPE,MAE,MSE,RMSE,MAPE,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,reg_alpha,reg_lambda,random_state,n_jobs
0,0.181444,12.333151,292.817515,17.037788,4.281339e+13,350,9,0.196506,0.744890,0.721959,1.787682,0.076529,42,-1
1,0.182102,12.370100,295.421751,17.181620,4.717426e+13,429,6,0.185022,0.989099,0.739021,2.142140,0.873499,42,-1
2,0.157256,10.682247,230.545965,15.131979,4.552123e+13,291,5,0.037532,0.736128,0.770772,1.803858,4.393623,42,-1
3,0.173845,11.811471,275.506119,16.561770,4.570822e+13,327,6,0.136025,0.803454,0.829167,3.719405,0.733147,42,-1
4,0.162582,11.041894,243.750572,15.561108,4.506827e+13,424,4,0.064522,0.859433,0.721795,0.969738,1.267592,42,-1
5,0.155989,10.601301,227.064016,14.978366,4.249791e+13,225,8,0.017261,0.910620,0.966614,0.234114,0.683733,42,-1
6,0.172241,11.698949,269.760568,16.406080,4.723654e+13,343,4,0.148668,0.764540,0.952581,0.082338,3.802815,42,-1
7,0.174971,11.892488,271.683715,16.404564,4.256351e+13,428,8,0.137586,0.954579,0.808006,3.445128,0.537452,42,-1
8,0.177326,12.048521,280.112093,16.706939,4.442491e+13,519,6,0.160988,0.842962,0.843139,2.921519,2.518588,42,-1
9,0.168926,11.482187,256.779562,15.941314,4.302469e+13,592,8,0.061261,0.899320,0.811673,3.493457,0.907301,42,-1
10,0.154594,10.505149,224.586029,14.896989,4.093089e+13,201,10,0.014511,0.917396,0.993056,4.703767,2.241611,42,-1
11,0.156475,10.632488,228.651866,15.036082,3.976262e+13,218,10,0.011059,0.915528,0.998255,4.779125,2.100675,42,-1
12,0.153911,10.458482,222.362506,14.824029,4.050377e+13,201,10,0.013961,0.920870,0.917014,4.824826,2.452832,42,-1
13,0.161635,10.985495,240.374340,15.407113,4.173182e+13,207,10,0.092218,0.996720,0.906506,4.953880,2.907225,42,-1
14,0.161128,10.950438,239.049593,15.369204,4.250954e+13,688,10,0.046485,0.940496,0.898930,4.258193,1.868873,42,-1
15,0.160106,10.880614,237.164433,15.327151,4.288407e+13,274,9,0.089828,0.865530,0.898934,4.256546,3.340032,42,-1
16,0.159728,10.856830,236.067529,15.263730,4.126691e+13,284,9,0.033523,0.954735,0.942222,4.314336,1.711273,42,-1
17,0.172368,11.714836,267.206440,16.295217,4.227987e+13,501,7,0.071386,0.817225,0.996847,2.717033,2.835195,42,-1
18,0.166288,11.291623,253.914077,15.903057,4.563598e+13,379,3,0.115377,0.889577,0.875245,4.592581,3.505485,42,-1
19,0.156370,10.624502,228.400832,15.049696,4.328997e+13,252,7,0.025154,0.939745,0.928637,3.496461,4.285343,42,-1
20,0.163631,11.120578,243.250311,15.531869,4.207957e+13,626,9,0.053309,0.701138,0.972108,3.998033,4.822066,42,-1
21,0.156980,10.665907,228.452268,15.033041,4.090601e+13,209,8,0.010788,0.912457,0.969063,0.407868,1.398147,42,-1
22,0.156096,10.609021,226.635050,14.959147,4.148630e+13,248,10,0.025065,0.886357,0.924026,0.704643,2.071273,42,-1
23,0.157074,10.675598,230.253692,15.078286,4.313995e+13,310,8,0.011925,0.926492,0.969870,2.914105,0.023698,42,-1
24,0.160604,10.914698,237.725287,15.338150,4.211473e+13,201,9,0.076858,0.979724,0.865677,1.012579,2.373088,42,-1
25,0.158321,10.760307,232.270291,15.147700,4.121318e+13,248,10,0.041007,0.880866,0.952688,1.265560,2.942397,42,-1
26,0.159009,10.804610,236.164978,15.297910,4.274216e+13,242,7,0.024723,0.969850,0.988884,2.241928,1.430845,42,-1
27,0.159700,10.853856,236.088753,15.279812,4.223894e+13,363,9,0.051459,0.840644,0.922193,3.153931,2.502893,42,-1
28,0.158460,10.770659,233.866819,15.185250,4.237796e+13,387,10,0.023058,0.913922,0.877181,4.535201,0.341771,42,-1
29,0.170191,11.566352,264.001930,16.192253,4.339900e+13,312,8,0.111187,0.819962,0.974839,1.667999,1.094561,42,-1

In [ ]:
df.to_csv('xgboost_errorfile_orders.csv', header=True, index=False)

In [17]:
study.best_params

{'n_estimators': 201,
 'max_depth': 10,
 'learning_rate': 0.013960663099383598,
 'subsample': 0.9208699091164867,
 'colsample_bytree': 0.9170140235850499,
 'reg_alpha': 4.824825650018285,
 'reg_lambda': 2.4528319109319674}

##**2. Sales**
---

In [40]:
train_df= load_data_dat('train_transformed_data.csv')
val_df= load_data_dat('validate_transformed_data.csv')
test_df= load_data_dat('test_data.csv')

In [41]:
train_df['Date'] = pd.to_datetime(train_df['Date'])
val_df['Date'] = pd.to_datetime(val_df['Date'])
train_df = train_df.sort_values("Date")
val_df = val_df.sort_values("Date")
train_df=train_df[FEATURES]
val_df=val_df[FEATURES]

In [46]:
def format_df_dtype(df, features_dtype_map_dict):
    for col, dtype in features_dtype_map_dict.items():
        if col in df.columns:
            df[col] = df[col].astype(dtype)
    return df

train_df = format_df_dtype(train_df, column_dtype_map_dict)
val_df = format_df_dtype(val_df, column_dtype_map_dict)

In [43]:
TARGET = "#Order"  # or "#Order"

X = train_df[FEATURES_ORDERS]
y = train_df[TARGET]

In [44]:
order_params = {
        'n_estimators': 201,
        'max_depth': 10,
        'learning_rate': 0.013960663099383598,
        'subsample': 0.9208699091164867,
        'colsample_bytree': 0.9170140235850499,
        'reg_alpha': 4.824825650018285,
        'reg_lambda': 2.4528319109319674
 }
model_orders = XGBRegressor(**order_params)

model_orders.fit(X, y)
X['pred_orders'] = model_orders.predict(X)

In [47]:
X.head()

,Store_id,Store_Type_S1,Store_Type_S2,Store_Type_S3,Store_Type_S4,Location_Type_L1,Location_Type_L2,Location_Type_L3,Location_Type_L4,Location_Type_L5,...,weekofyear,is_weekend,lag_1_#Order,lag_7_#Order,rolling_#Order_7,lag_1_Sales,lag_7_Sales,rolling_Sales_7,lag_1_aov,pred_orders
0,1,1,0,0,0,0,0,1,0,0,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.546566
59796,152,0,1,0,0,1,0,0,0,0,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.724590
116820,296,1,0,0,0,1,0,0,0,0,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.487133
27324,70,1,0,0,0,1,0,0,0,0,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.832047
117216,297,0,1,0,0,0,0,1,0,0,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.585300

In [48]:
TARGET = 'Sales'
y = train_df[TARGET]

In [53]:
tscv = TimeSeriesSplit(n_splits=3)
mean_metric_scores = []
def objective(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 700),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "subsample": trial.suggest_float("subsample", 0.7, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.7, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0, 5),
        "reg_lambda": trial.suggest_float("reg_lambda", 0, 5),
        "random_state": 42,
        "n_jobs": -1
    }

    wape_scores = []
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    mape_scores = []

    for train_idx, val_idx in tscv.split(X):

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        model = XGBRegressor(**params)
        model.fit(X_train_fold, y_train_fold)

        preds = model.predict(X_val_fold)
        #score = mean_absolute_error(y_val_fold, preds)
        #score = wape(y_val_fold, preds)

        wape_scores.append(wape(y_val_fold, preds))
        mae_scores.append(mean_absolute_error(y_val_fold, preds))
        mse_scores.append(mean_squared_error(y_val_fold, preds))
        rmse_scores.append(np.sqrt(mean_squared_error(y_val_fold, preds)))
        #mape_scores.append(mape(y_val_fold, preds))

    average_metric = np.mean(mae_scores)
    mean_score = mean_metric_scores.append((
                                np.mean(wape_scores), 
                                np.mean(mae_scores), 
                                np.mean(mse_scores), 
                                np.mean(rmse_scores), 
                                0,  # Placeholder for MAPE since it's commented out
                                params
                            ))
    return average_metric

In [54]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Score:", study.best_value)

[I 2026-04-20 18:36:29,951] A new study created in memory with name: no-name-37b272fa-ecdf-4649-8328-4f32a586cf0a
[I 2026-04-20 18:36:39,324] Trial 0 finished with value: 5386.10802150514 and parameters: {'n_estimators': 628, 'max_depth': 3, 'learning_rate': 0.13575703472513576, 'subsample': 0.990875132016154, 'colsample_bytree': 0.7957166738643743, 'reg_alpha': 2.864196070616416, 'reg_lambda': 2.4928736161292466}. Best is trial 0 with value: 5386.10802150514.
[I 2026-04-20 18:36:46,501] Trial 1 finished with value: 5235.009043998417 and parameters: {'n_estimators': 294, 'max_depth': 3, 'learning_rate': 0.018897751584733488, 'subsample': 0.7032071018245494, 'colsample_bytree': 0.9463830808167368, 'reg_alpha': 3.559519819927001, 'reg_lambda': 2.601144528095566}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:37:15,384] Trial 2 finished with value: 5325.454030882815 and parameters: {'n_estimators': 210, 'max_depth': 10, 'learning_rate': 0.06469396231641392, 'subsample': 0.8839331668820507, 'colsample_bytree': 0.9849935958634616, 'reg_alpha': 0.19844234524348303, 'reg_lambda': 0.7040665406013691}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:37:25,481] Trial 3 finished with value: 6115.378303187995 and parameters: {'n_estimators': 209, 'max_depth': 7, 'learning_rate': 0.18883241641745485, 'subsample': 0.8490325374671286, 'colsample_bytree': 0.8217622987111429, 'reg_alpha': 4.771291881494595, 'reg_lambda': 0.6295733225724276}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:37:41,755] Trial 4 finished with value: 5262.097789214563 and parameters: {'n_estimators': 452, 'max_depth': 6, 'learning_rate': 0.031910812625704305, 'subsample': 0.7861539969198436, 'colsample_bytree': 0.8022335699391465, 'reg_alpha': 2.8002684086263137, 'reg_lambda': 3.6645889145467025}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:37:52,344] Trial 5 finished with value: 5486.49360814075 and parameters: {'n_estimators': 561, 'max_depth': 3, 'learning_rate': 0.16293709188264416, 'subsample': 0.8051483010843308, 'colsample_bytree': 0.7022316033669207, 'reg_alpha': 0.2656656715831962, 'reg_lambda': 1.6116892576668125}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:38:04,590] Trial 6 finished with value: 5960.3886919691895 and parameters: {'n_estimators': 360, 'max_depth': 6, 'learning_rate': 0.13994960073175136, 'subsample': 0.9881038151170428, 'colsample_bytree': 0.79282260830257, 'reg_alpha': 2.7719868959461174, 'reg_lambda': 4.035886502861337}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:38:19,658] Trial 7 finished with value: 5329.379126608191 and parameters: {'n_estimators': 228, 'max_depth': 8, 'learning_rate': 0.049604889460128795, 'subsample': 0.9488995439299452, 'colsample_bytree': 0.9242771882347721, 'reg_alpha': 3.4950234069584822, 'reg_lambda': 1.913338371521599}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:38:37,848] Trial 8 finished with value: 5380.8769541834945 and parameters: {'n_estimators': 259, 'max_depth': 8, 'learning_rate': 0.06703786157972066, 'subsample': 0.7035143833824806, 'colsample_bytree': 0.9315993447949416, 'reg_alpha': 1.9037764364751808, 'reg_lambda': 2.2146250437242747}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:38:53,182] Trial 9 finished with value: 5255.303173775222 and parameters: {'n_estimators': 325, 'max_depth': 7, 'learning_rate': 0.05920049203194683, 'subsample': 0.7562716589269561, 'colsample_bytree': 0.9421060983629341, 'reg_alpha': 4.971988335562855, 'reg_lambda': 4.140517638851317}. Best is trial 1 with value: 5235.009043998417.
[I 2026-04-20 18:39:04,810] Trial 10 finished with value: 5159.7308142633165 and parameters: {'n_estimators': 447, 'max_depth': 4, 'learning_rate': 0.012096631544838482, 'subsample': 0.7033310699946133, 'colsample_bytree': 0.8625861977938118, 'reg_alpha': 1.4872695357766728, 'reg_lambda': 4.953827272890042}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:39:16,448] Trial 11 finished with value: 5165.66404423525 and parameters: {'n_estimators': 466, 'max_depth': 4, 'learning_rate': 0.018148552986109002, 'subsample': 0.7081313646453601, 'colsample_bytree': 0.8798383333751958, 'reg_alpha': 1.526695697516167, 'reg_lambda': 3.0819413507423863}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:39:28,525] Trial 12 finished with value: 5191.818316017986 and parameters: {'n_estimators': 471, 'max_depth': 4, 'learning_rate': 0.011660886408829396, 'subsample': 0.7454864601432024, 'colsample_bytree': 0.8613531742323343, 'reg_alpha': 1.450488381860298, 'reg_lambda': 4.994015673776168}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:39:42,853] Trial 13 finished with value: 5528.9431882544595 and parameters: {'n_estimators': 533, 'max_depth': 5, 'learning_rate': 0.07706277766749828, 'subsample': 0.7538753010943259, 'colsample_bytree': 0.8651690226154038, 'reg_alpha': 1.2161369877381913, 'reg_lambda': 4.911418058799891}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:39:53,978] Trial 14 finished with value: 5529.214773124771 and parameters: {'n_estimators': 390, 'max_depth': 5, 'learning_rate': 0.09370265459575304, 'subsample': 0.8617434589280847, 'colsample_bytree': 0.8941951262193182, 'reg_alpha': 0.9026426923189468, 'reg_lambda': 2.8875212514461275}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:40:08,682] Trial 15 finished with value: 5271.2709406261165 and parameters: {'n_estimators': 686, 'max_depth': 4, 'learning_rate': 0.03710217352025831, 'subsample': 0.8112727103946632, 'colsample_bytree': 0.7552945558142669, 'reg_alpha': 1.8958470492257902, 'reg_lambda': 3.3943656183278685}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:40:23,349] Trial 16 finished with value: 6574.0804643313495 and parameters: {'n_estimators': 525, 'max_depth': 5, 'learning_rate': 0.1101163172372748, 'subsample': 0.7265077058373022, 'colsample_bytree': 0.8836998646487269, 'reg_alpha': 2.032015833904122, 'reg_lambda': 0.01761723669746118}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:40:34,145] Trial 17 finished with value: 5203.1046393666975 and parameters: {'n_estimators': 404, 'max_depth': 4, 'learning_rate': 0.011174832607995698, 'subsample': 0.776346823871965, 'colsample_bytree': 0.8412771693041587, 'reg_alpha': 0.6959219476718933, 'reg_lambda': 4.4145064404131995}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:41:35,394] Trial 18 finished with value: 5294.274804427516 and parameters: {'n_estimators': 492, 'max_depth': 10, 'learning_rate': 0.040458503247022826, 'subsample': 0.9024877568429224, 'colsample_bytree': 0.8969995348733747, 'reg_alpha': 1.5075449067767068, 'reg_lambda': 3.2028768253981363}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:41:49,120] Trial 19 finished with value: 5559.948875620435 and parameters: {'n_estimators': 592, 'max_depth': 4, 'learning_rate': 0.10013369354479565, 'subsample': 0.72496809190655, 'colsample_bytree': 0.9903255333042524, 'reg_alpha': 2.392308891151261, 'reg_lambda': 1.4229332392402534}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:42:00,342] Trial 20 finished with value: 5575.199940870337 and parameters: {'n_estimators': 387, 'max_depth': 5, 'learning_rate': 0.08336017446102548, 'subsample': 0.8245628035802336, 'colsample_bytree': 0.7427653467360797, 'reg_alpha': 0.897551535173802, 'reg_lambda': 3.7523852869380154}. Best is trial 10 with value: 5159.7308142633165.
[I 2026-04-20 18:42:11,229] Trial 21 finished with value: 5133.646753340158 and parameters: {'n_estimators': 425, 'max_depth': 4, 'learning_rate': 0.021091177254039396, 'subsample': 0.7409097497514677, 'colsample_bytree': 0.8471944397246882, 'reg_alpha': 1.4729933520125358, 'reg_lambda': 4.981868564593667}. Best is trial 21 with value: 5133.646753340158.
[I 2026-04-20 18:42:22,122] Trial 22 finished with value: 5159.024111128497 and parameters: {'n_estimators': 427, 'max_depth': 4, 'learning_rate': 0.026998766721338607, 'subsample': 0.7012207448351825, 'colsample_bytree': 0.8327650051240363, 'reg_alpha': 1.6275700094087204, 'reg_lambda': 4.562018519616048}. Best is trial 21 with value: 5133.646753340158.
[I 2026-04-20 18:42:29,769] Trial 23 finished with value: 5194.0454471029325 and parameters: {'n_estimators': 428, 'max_depth': 3, 'learning_rate': 0.03177952355837627, 'subsample': 0.7341660990490547, 'colsample_bytree': 0.8298113931335542, 'reg_alpha': 2.1922535873091333, 'reg_lambda': 4.629372889082841}. Best is trial 21 with value: 5133.646753340158.
[I 2026-04-20 18:42:42,552] Trial 24 finished with value: 5309.350925274434 and parameters: {'n_estimators': 346, 'max_depth': 6, 'learning_rate': 0.04574798433004698, 'subsample': 0.7649645400989262, 'colsample_bytree': 0.7657427653270792, 'reg_alpha': 0.528990548918961, 'reg_lambda': 4.446456405195322}. Best is trial 21 with value: 5133.646753340158.
[I 2026-04-20 18:42:58,430] Trial 25 finished with value: 5160.908736424426 and parameters: {'n_estimators': 504, 'max_depth': 5, 'learning_rate': 0.02578768280637129, 'subsample': 0.7275846890862059, 'colsample_bytree': 0.846695793332672, 'reg_alpha': 1.1991054430949704, 'reg_lambda': 4.6869278451103265}. Best is trial 21 with value: 5133.646753340158.
[I 2026-04-20 18:43:06,938] Trial 26 finished with value: 5239.668162384673 and parameters: {'n_estimators': 430, 'max_depth': 4, 'learning_rate': 0.06076672802315085, 'subsample': 0.7865866763722532, 'colsample_bytree': 0.8172224998868168, 'reg_alpha': 1.6371090112047921, 'reg_lambda': 4.129880573816597}. Best is trial 21 with value: 5133.646753340158.
[I 2026-04-20 18:43:15,652] Trial 27 finished with value: 5165.18081374033 and parameters: {'n_estimators': 424, 'max_depth': 3, 'learning_rate': 0.047298934589975625, 'subsample': 0.7042287903181706, 'colsample_bytree': 0.9104645275407726, 'reg_alpha': 3.2123405099225826, 'reg_lambda': 3.77174148944792}. Best is trial 21 with value: 5133.646753340158.
[I 2026-04-20 18:43:25,951] Trial 28 finished with value: 5099.497391305139 and parameters: {'n_estimators': 323, 'max_depth': 5, 'learning_rate': 0.026530195738347556, 'subsample': 0.7388544536271039, 'colsample_bytree': 0.8628252390092686, 'reg_alpha': 1.1499809816719329, 'reg_lambda': 4.984633296547041}. Best is trial 28 with value: 5099.497391305139.
[I 2026-04-20 18:43:36,697] Trial 29 finished with value: 5665.188824531974 and parameters: {'n_estimators': 294, 'max_depth': 6, 'learning_rate': 0.12604396185159059, 'subsample': 0.7434141609232204, 'colsample_bytree': 0.7930639432919299, 'reg_alpha': 1.0758215685169314, 'reg_lambda': 4.360153360566684}. Best is trial 28 with value: 5099.497391305139.

Best Params: {'n_estimators': 323, 'max_depth': 5, 'learning_rate': 0.026530195738347556, 'subsample': 0.7388544536271039, 'colsample_bytree': 0.8628252390092686, 'reg_alpha': 1.1499809816719329, 'reg_lambda': 4.984633296547041}
Best Score: 5099.497391305139

In [55]:
formatted_data = []
for wape, mae, mse, rmse, mape, params in mean_metric_scores:
    # Combine metrics and the params dictionary into one flat dict
    row = {
        'WAPE': wape, 'MAE': mae, 'MSE': mse, 
        'RMSE': rmse, 'MAPE': mape
    }
    row.update(params)
    formatted_data.append(row)

df = pd.DataFrame(formatted_data)
df

,WAPE,MAE,MSE,RMSE,MAPE,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,reg_alpha,reg_lambda,random_state,n_jobs
0,0.125849,5386.108022,5.255823e+07,7235.936311,0,628,3,0.135757,0.990875,0.795717,2.864196,2.492874,42,-1
1,0.122172,5235.009044,5.284561e+07,7244.371328,0,294,3,0.018898,0.703207,0.946383,3.559520,2.601145,42,-1
2,0.124417,5325.454031,5.206890e+07,7201.318061,0,210,10,0.064694,0.883933,0.984994,0.198442,0.704067,42,-1
3,0.142943,6115.378303,6.635783e+07,8121.356304,0,209,7,0.188832,0.849033,0.821762,4.771292,0.629573,42,-1
4,0.122858,5262.097789,5.114767e+07,7131.520278,0,452,6,0.031911,0.786154,0.802234,2.800268,3.664589,42,-1
5,0.128125,5486.493608,5.462399e+07,7371.392427,0,561,3,0.162937,0.805148,0.702232,0.265666,1.611689,42,-1
6,0.139685,5960.388692,6.261322e+07,7897.627862,0,360,6,0.139950,0.988104,0.792823,2.771987,4.035887,42,-1
7,0.124434,5329.379127,5.189228e+07,7184.777887,0,228,8,0.049605,0.948900,0.924277,3.495023,1.913338,42,-1
8,0.125722,5380.876954,5.276058e+07,7246.500457,0,259,8,0.067038,0.703514,0.931599,1.903776,2.214625,42,-1
9,0.122809,5255.303174,5.065923e+07,7101.575188,0,325,7,0.059200,0.756272,0.942106,4.971988,4.140518,42,-1
10,0.120456,5159.730814,5.092490e+07,7115.371146,0,447,4,0.012097,0.703331,0.862586,1.487270,4.953827,42,-1
11,0.120615,5165.664044,5.021984e+07,7068.190444,0,466,4,0.018149,0.708131,0.879838,1.526696,3.081941,42,-1
12,0.121213,5191.818316,5.143034e+07,7151.060149,0,471,4,0.011661,0.745486,0.861353,1.450488,4.994016,42,-1
13,0.129325,5528.943188,5.487031e+07,7391.372977,0,533,5,0.077063,0.753875,0.865169,1.216137,4.911418,42,-1
14,0.129274,5529.214773,5.478314e+07,7385.869098,0,390,5,0.093703,0.861743,0.894195,0.902643,2.887521,42,-1
15,0.122990,5271.270941,5.120595e+07,7131.704676,0,686,4,0.037102,0.811273,0.755295,1.895847,3.394366,42,-1
16,0.154043,6574.080464,7.650442e+07,8673.355265,0,525,5,0.110116,0.726508,0.883700,2.032016,0.017617,42,-1
17,0.121456,5203.104639,5.204227e+07,7190.666865,0,404,4,0.011175,0.776347,0.841277,0.695922,4.414506,42,-1
18,0.123701,5294.274804,5.156512e+07,7164.843750,0,492,10,0.040459,0.902488,0.897000,1.507545,3.202877,42,-1
19,0.129850,5559.948876,5.577346e+07,7436.719947,0,592,4,0.100134,0.724968,0.990326,2.392309,1.422933,42,-1
20,0.130406,5575.199941,5.577090e+07,7454.555301,0,387,5,0.083360,0.824563,0.742765,0.897552,3.752385,42,-1
21,0.119849,5133.646753,4.980674e+07,7037.856651,0,425,4,0.021091,0.740910,0.847194,1.472993,4.981869,42,-1
22,0.120456,5159.024111,4.982006e+07,7039.938178,0,427,4,0.026999,0.701221,0.832765,1.627570,4.562019,42,-1
23,0.121249,5194.045447,5.064340e+07,7095.919362,0,428,3,0.031780,0.734166,0.829811,2.192254,4.629373,42,-1
24,0.123972,5309.350925,5.169622e+07,7171.249088,0,346,6,0.045748,0.764965,0.765743,0.528991,4.446456,42,-1
25,0.120474,5160.908736,4.959549e+07,7021.822700,0,504,5,0.025788,0.727585,0.846696,1.199105,4.686928,42,-1
26,0.122300,5239.668162,5.075863e+07,7100.249800,0,430,4,0.060767,0.786587,0.817222,1.637109,4.129881,42,-1
27,0.120548,5165.180814,4.968721e+07,7025.856537,0,424,3,0.047299,0.704229,0.910465,3.212341,3.771741,42,-1
28,0.119079,5099.497391,4.903687e+07,6984.439792,0,323,5,0.026530,0.738854,0.862825,1.149981,4.984633,42,-1
29,0.132541,5665.188825,5.792692e+07,7591.980339,0,294,6,0.126044,0.743414,0.793064,1.075822,4.360153,42,-1

In [56]:
df.to_csv('xgboost_errorfile_sales.csv', header=True, index=False)

In [57]:
study.best_params

{'n_estimators': 323,
 'max_depth': 5,
 'learning_rate': 0.026530195738347556,
 'subsample': 0.7388544536271039,
 'colsample_bytree': 0.8628252390092686,
 'reg_alpha': 1.1499809816719329,
 'reg_lambda': 4.984633296547041}