In [1]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [16]:
import os
import numpy as np
import pandas as pd

In [17]:
import gdown
import optuna
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_absolute_percentage_error as mape
from sklearn.linear_model import Ridge

tscv = TimeSeriesSplit(n_splits=3)

In [18]:
import warnings
warnings.filterwarnings('ignore')

In [19]:
datafile_dict={
    "train_transformed_data.csv": "1w_ZOLTTc8WnLj7l8bnwo8Vuz1ii_ZBTY"
    ,"validate_transformed_data.csv" : "1SI5pS8igjgATw5fSPB8hYt5vc62aiVHF"
    ,"test_data.csv" : "1JhzqIAupBjD-vZTqnaAqL1OI9HIpD9O6"
}
#remove existing files
for filename in datafile_dict.keys():
    if os.path.exists(filename):
        os.remove(filename)
        print(f"Removed {filename}")
    else:
        print(f"{filename} not found, skipping removal.")
#doanload new files from drive
for filename, file_id in datafile_dict.items():
  gdown.download(id=file_id, output=filename, quiet=False)

Removed train_transformed_data.csv
Removed validate_transformed_data.csv
Removed test_data.csv

Downloading...
From: https://drive.google.com/uc?id=1w_ZOLTTc8WnLj7l8bnwo8Vuz1ii_ZBTY
To: /content/train_transformed_data.csv
100%|██████████| 28.5M/28.5M [00:00<00:00, 190MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SI5pS8igjgATw5fSPB8hYt5vc62aiVHF
To: /content/validate_transformed_data.csv
100%|██████████| 6.29M/6.29M [00:00<00:00, 123MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JhzqIAupBjD-vZTqnaAqL1OI9HIpD9O6
To: /content/test_data.csv
100%|██████████| 572k/572k [00:00<00:00, 87.2MB/s]

In [20]:
def load_data_dat(filename):
  if filename.endswith('.csv'):
    df=pd.read_csv(filename)
  return df

train_df= load_data_dat('train_transformed_data.csv')
val_df= load_data_dat('validate_transformed_data.csv')
test_df= load_data_dat('test_data.csv')

In [21]:
FEATURES = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_aov',
    'Sales','#Order'
]
FEATURES_ORDERS = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_aov'
]

FEATURES_SALES = [
    'Store_id',#'Store_Type','Location_Type','Region_Code',
    'Store_Type_S1',
       'Store_Type_S2', 'Store_Type_S3', 'Store_Type_S4', 'Location_Type_L1',
       'Location_Type_L2', 'Location_Type_L3', 'Location_Type_L4',
       'Location_Type_L5', 'Region_Code_R1', 'Region_Code_R2',
       'Region_Code_R3', 'Region_Code_R4',
    'Discount_Flag','Holiday',
    'day','month','weekday','weekofyear','is_weekend',
    'lag_1_Sales','lag_7_Sales','rolling_Sales_7',
    'lag_1_#Order','lag_7_#Order','rolling_#Order_7',
    'lag_1_aov','pred_orders'
]

column_dtype_map_dict = {'Store_id': 'int64',
 'Store_Type_S1': 'int64',
 'Store_Type_S2': 'int64',
 'Store_Type_S3': 'int64',
 'Store_Type_S4': 'int64',
 'Location_Type_L1': 'int64',
 'Location_Type_L2': 'int64',
 'Location_Type_L3': 'int64',
 'Location_Type_L4': 'int64',
 'Location_Type_L5': 'int64',
 'Region_Code_R1': 'int64',
 'Region_Code_R2': 'int64',
 'Region_Code_R3': 'int64',
 'Region_Code_R4': 'int64',
 'Discount_Flag': 'int64',
 'Holiday': 'int64',
 'day': 'int64',
 'month': 'int64',
 'weekday': 'int64',
 'weekofyear': 'int64',
 'is_weekend': 'int64',
 'lag_1_#Order': 'float64',
 'lag_7_#Order': 'float64',
 'rolling_#Order_7': 'float64',
 'lag_1_Sales': 'float64',
 'lag_7_Sales': 'float64',
 'rolling_Sales_7': 'float64',
 'lag_1_aov': 'float64',
 'Sales': 'float64',
 '#Order': 'float64',
 'pred_orders': 'float64'}

In [22]:
train_df['Date'] = pd.to_datetime(train_df['Date'])
val_df['Date'] = pd.to_datetime(val_df['Date'])
train_df = train_df.sort_values("Date")
val_df = val_df.sort_values("Date")
train_df=train_df[FEATURES]
val_df=val_df[FEATURES]

In [23]:
def format_df_dtype(df, features_dtype_map_dict):
    for col, dtype in features_dtype_map_dict.items():
        if col in df.columns:
            df[col] = df[col].astype(dtype)
    return df

train_df = format_df_dtype(train_df, column_dtype_map_dict)
val_df = format_df_dtype(val_df, column_dtype_map_dict)

#**Ridge**
---

##**1. Orders**
---

In [24]:
TARGET = "#Order"  # or "#Order"
train_df2=train_df.copy(deep=True).dropna()
X = train_df2[FEATURES_ORDERS]
y = train_df2[TARGET]

In [41]:
def wape(y_true, y_pred):
    return np.sum(np.abs(y_true - y_pred)) / (np.sum(y_true) + 1e-8)

In [26]:
tscv = TimeSeriesSplit(n_splits=3)
mean_metric_scores = []
def objective(trial):

    params = {
        "alpha": trial.suggest_float("alpha", 0.1, 50)
    }

    wape_scores = []
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    mape_scores = []

    for train_idx, val_idx in tscv.split(X):

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        model = Ridge(**params)
        model.fit(X_train_fold, y_train_fold)

        preds = model.predict(X_val_fold)
        #score = mean_absolute_error(y_val_fold, preds)
        #score = wape(y_val_fold, preds)

        wape_scores.append(wape(y_val_fold, preds))
        mae_scores.append(mean_absolute_error(y_val_fold, preds))
        mse_scores.append(mean_squared_error(y_val_fold, preds))
        rmse_scores.append(np.sqrt(mean_squared_error(y_val_fold, preds)))
        mape_scores.append(mape(y_val_fold, preds))

    average_metric = np.mean(mae_scores)
    mean_score = mean_metric_scores.append((np.mean(wape_scores),np.mean(mae_scores),np.mean(mse_scores),np.mean(rmse_scores),np.mean(mape_scores),params))
    return average_metric

In [27]:

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Score:", study.best_value)

[I 2026-04-20 19:56:02,844] A new study created in memory with name: no-name-23f2fe6a-709b-4323-aaa4-51cc32ed68f5
[I 2026-04-20 19:56:03,002] Trial 0 finished with value: 10.580634438659338 and parameters: {'alpha': 18.13636412778741}. Best is trial 0 with value: 10.580634438659338.
[I 2026-04-20 19:56:03,140] Trial 1 finished with value: 10.65858717002159 and parameters: {'alpha': 5.407462241711664}. Best is trial 0 with value: 10.580634438659338.
[I 2026-04-20 19:56:03,278] Trial 2 finished with value: 10.660814733612437 and parameters: {'alpha': 5.127316596971664}. Best is trial 0 with value: 10.580634438659338.
[I 2026-04-20 19:56:03,422] Trial 3 finished with value: 10.554266257414783 and parameters: {'alpha': 24.143467130042822}. Best is trial 3 with value: 10.554266257414783.
[I 2026-04-20 19:56:03,593] Trial 4 finished with value: 10.548814670195325 and parameters: {'alpha': 25.529628685653346}. Best is trial 4 with value: 10.548814670195325.
[I 2026-04-20 19:56:03,734] Trial 5 finished with value: 10.518549106079897 and parameters: {'alpha': 34.31724252806238}. Best is trial 5 with value: 10.518549106079897.
[I 2026-04-20 19:56:03,876] Trial 6 finished with value: 10.53664247014279 and parameters: {'alpha': 28.828440177406367}. Best is trial 5 with value: 10.518549106079897.
[I 2026-04-20 19:56:04,019] Trial 7 finished with value: 10.50807149431857 and parameters: {'alpha': 37.86139322129081}. Best is trial 7 with value: 10.50807149431857.
[I 2026-04-20 19:56:04,173] Trial 8 finished with value: 10.593061812154717 and parameters: {'alpha': 15.657870955914978}. Best is trial 7 with value: 10.50807149431857.
[I 2026-04-20 19:56:04,351] Trial 9 finished with value: 10.563186268303843 and parameters: {'alpha': 21.987625759268848}. Best is trial 7 with value: 10.50807149431857.
[I 2026-04-20 19:56:04,495] Trial 10 finished with value: 10.480065000139682 and parameters: {'alpha': 48.96629503181593}. Best is trial 10 with value: 10.480065000139682.
[I 2026-04-20 19:56:04,657] Trial 11 finished with value: 10.480662238688756 and parameters: {'alpha': 48.70093528829212}. Best is trial 10 with value: 10.480065000139682.
[I 2026-04-20 19:56:04,800] Trial 12 finished with value: 10.479540738301528 and parameters: {'alpha': 49.20032482199344}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:04,952] Trial 13 finished with value: 10.483056815565917 and parameters: {'alpha': 47.65037493921785}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:05,137] Trial 14 finished with value: 10.49626885283964 and parameters: {'alpha': 42.2222179680022}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:05,382] Trial 15 finished with value: 10.50082619528945 and parameters: {'alpha': 40.489613773783084}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:05,558] Trial 16 finished with value: 10.480438817629953 and parameters: {'alpha': 48.80004808142968}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:05,797] Trial 17 finished with value: 10.527944697224056 and parameters: {'alpha': 31.373703247746793}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:06,120] Trial 18 finished with value: 10.495267682770233 and parameters: {'alpha': 42.61150974229656}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:06,421] Trial 19 finished with value: 10.514172092375263 and parameters: {'alpha': 35.76253120060036}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:06,643] Trial 20 finished with value: 10.491801583059548 and parameters: {'alpha': 43.99023015567205}. Best is trial 12 with value: 10.479540738301528.
[I 2026-04-20 19:56:06,951] Trial 21 finished with value: 10.478464962797675 and parameters: {'alpha': 49.6838594031875}. Best is trial 21 with value: 10.478464962797675.
[I 2026-04-20 19:56:07,196] Trial 22 finished with value: 10.477927666749991 and parameters: {'alpha': 49.927017883207526}. Best is trial 22 with value: 10.477927666749991.
[I 2026-04-20 19:56:07,368] Trial 23 finished with value: 10.490653472231783 and parameters: {'alpha': 44.45558852163887}. Best is trial 22 with value: 10.477927666749991.
[I 2026-04-20 19:56:07,560] Trial 24 finished with value: 10.505036681343645 and parameters: {'alpha': 38.94378606929392}. Best is trial 22 with value: 10.477927666749991.
[I 2026-04-20 19:56:07,854] Trial 25 finished with value: 10.487999622203729 and parameters: {'alpha': 45.548233405310995}. Best is trial 22 with value: 10.477927666749991.
[I 2026-04-20 19:56:08,103] Trial 26 finished with value: 10.47794458186689 and parameters: {'alpha': 49.91934506424742}. Best is trial 22 with value: 10.477927666749991.
[I 2026-04-20 19:56:08,345] Trial 27 finished with value: 10.48939469564965 and parameters: {'alpha': 44.97088190571067}. Best is trial 22 with value: 10.477927666749991.
[I 2026-04-20 19:56:08,581] Trial 28 finished with value: 10.613121750384293 and parameters: {'alpha': 12.058768497379901}. Best is trial 22 with value: 10.477927666749991.
[I 2026-04-20 19:56:08,838] Trial 29 finished with value: 10.704064235122567 and parameters: {'alpha': 0.3985792007362363}. Best is trial 22 with value: 10.477927666749991.

Best Params: {'alpha': 49.927017883207526}
Best Score: 10.477927666749991

In [28]:
formatted_data = []
for wape, mae, mse, rmse, mape, params in mean_metric_scores:
    # Combine metrics and the params dictionary into one flat dict
    row = {
        'WAPE': wape, 'MAE': mae, 'MSE': mse, 
        'RMSE': rmse, 'MAPE': mape
    }
    row.update(params)
    formatted_data.append(row)

df = pd.DataFrame(formatted_data)
df

        WAPE        MAE         MSE       RMSE          MAPE      alpha
0   0.155943  10.580634  240.409418  15.338004  3.830445e+13  18.136364
1   0.157100  10.658587  251.015777  15.625077  3.839975e+13   5.407462
2   0.157133  10.660815  251.330368  15.633427  3.840259e+13   5.127317
3   0.155552  10.554266  237.114504  15.246389  3.827468e+13  24.143467
4   0.155471  10.548815  236.458199  15.227988  3.826872e+13  25.529629
5   0.155022  10.518549  232.988666  15.129834  3.823686e+13  34.317243
6   0.155290  10.536642  235.026396  15.187664  3.825564e+13  28.828440
7   0.154866  10.508071  231.861389  15.097612  3.822635e+13  37.861393
8   0.156128  10.593062  242.024345  15.382460  3.831896e+13  15.657871
9   0.155684  10.563186  238.207410  15.276916  3.828459e+13  21.987626
10  0.154451  10.480065  229.045963  15.016388  3.819966e+13  48.966295
11  0.154460  10.480662  229.102887  15.018041  3.820020e+13  48.700935
12  0.154443  10.479541  228.996119  15.014940  3.819918e+13  49.200325
13  0.154495  10.483057  229.332592  15.024707  3.820241e+13  47.650375
14  0.154691  10.496269  230.640364  15.062519  3.821486e+13  42.222218
15  0.154759  10.500826  231.105465  15.075910  3.821925e+13  40.489614
16  0.154457  10.480439  229.081575  15.017422  3.820000e+13  48.800048
17  0.155161  10.527945  234.032826  15.159533  3.824651e+13  31.373703
18  0.154677  10.495268  230.539258  15.059605  3.821390e+13  42.611510
19  0.154957  10.514172  232.512944  15.116256  3.823243e+13  35.762531
20  0.154625  10.491802  230.190726  15.049546  3.821060e+13  43.990230
21  0.154427  10.478465  228.894189  15.011978  3.819820e+13  49.683859
22  0.154419  10.477928  228.843461  15.010503  3.819771e+13  49.927018
23  0.154608  10.490653  230.076345  15.046241  3.820951e+13  44.455589
24  0.154821  10.505037  231.542367  15.088462  3.822336e+13  38.943786
25  0.154569  10.488000  229.813993  15.038654  3.820701e+13  45.548233
26  0.154420  10.477945  228.845056  15.010549  3.819772e+13  49.919345
27  0.154589  10.489395  229.951548  15.042633  3.820832e+13  44.970882
28  0.156426  10.613122  244.703216  15.455586  3.834299e+13  12.058768
29  0.157774  10.704064  257.425861  15.793616  3.845808e+13   0.398579

In [29]:
df.to_csv('ridge_errorfile_orders.csv', header=True, index=False)

In [30]:
study.best_params

{'alpha': 49.927017883207526}

##**2. Sales**
---

In [42]:
train_df= load_data_dat('train_transformed_data.csv')
val_df= load_data_dat('validate_transformed_data.csv')
test_df= load_data_dat('test_data.csv')

In [43]:
train_df['Date'] = pd.to_datetime(train_df['Date'])
val_df['Date'] = pd.to_datetime(val_df['Date'])
train_df = train_df.sort_values("Date")
val_df = val_df.sort_values("Date")
train_df=train_df[FEATURES]
val_df=val_df[FEATURES]

In [44]:
def format_df_dtype(df, features_dtype_map_dict):
    for col, dtype in features_dtype_map_dict.items():
        if col in df.columns:
            df[col] = df[col].astype(dtype)
    return df

train_df = format_df_dtype(train_df, column_dtype_map_dict)
val_df = format_df_dtype(val_df, column_dtype_map_dict)

In [45]:
TARGET = "#Order"  # or "#Order"
train_df2=train_df.copy(deep=True).dropna()
X = train_df2[FEATURES_ORDERS]
y = train_df2[TARGET]

In [53]:
order_params = {
            'alpha': 49.927017883207526
            }
model_orders = Ridge(**order_params)

model_orders.fit(X, y)
X['pred_orders'] = model_orders.predict(X)

In [54]:
X[X['Store_id'] == 1].head(10)

,Store_id,Store_Type_S1,Store_Type_S2,Store_Type_S3,Store_Type_S4,Location_Type_L1,Location_Type_L2,Location_Type_L3,Location_Type_L4,Location_Type_L5,...,weekofyear,is_weekend,lag_1_#Order,lag_7_#Order,rolling_#Order_7,lag_1_Sales,lag_7_Sales,rolling_Sales_7,lag_1_aov,pred_orders
7,1,1,0,0,0,0,0,1,0,0,...,2,0,55.0,9.0,51.285714,36855.0,7011.84,36109.834286,658.125000,30688.246189
8,1,1,0,0,0,0,0,1,0,0,...,2,0,52.0,60.0,57.428571,34101.0,42369.00,39979.714286,643.415094,29898.437639
9,1,1,0,0,0,0,0,1,0,0,...,2,0,65.0,72.0,58.142857,42429.0,50037.00,39988.285714,642.863636,30960.646132
10,1,1,0,0,0,0,0,1,0,0,...,2,0,53.0,64.0,55.428571,33510.0,44397.00,37627.285714,620.555556,28097.276646
11,1,1,0,0,0,0,0,1,0,0,...,2,0,56.0,63.0,54.285714,36873.0,47604.00,36552.428571,646.894737,28662.406180
12,1,1,0,0,0,0,0,1,0,0,...,2,1,35.0,36.0,50.285714,25644.0,24495.00,33415.285714,712.333333,46553.634931
13,1,1,0,0,0,0,0,1,0,0,...,2,1,57.0,55.0,53.285714,40890.0,36855.00,35757.428571,705.000000,40655.018561
14,1,1,0,0,0,0,0,1,0,0,...,3,0,56.0,52.0,53.428571,39254.4,34101.00,36100.200000,688.673684,41836.686074
15,1,1,0,0,0,0,0,1,0,0,...,3,0,78.0,65.0,57.142857,51993.0,42429.00,38656.200000,658.139241,44855.883471
16,1,1,0,0,0,0,0,1,0,0,...,3,0,64.0,53.0,57.000000,37716.0,33510.00,37982.914286,580.246154,41705.551210

In [55]:
TARGET = 'Sales'
y = train_df2[TARGET]

In [61]:
tscv = TimeSeriesSplit(n_splits=3)
mean_metric_scores = []
def objective(trial):

    params = {
        "alpha": trial.suggest_float("alpha", 0.1, 50)
    }

    wape_scores = []
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    mape_scores = []

    for train_idx, val_idx in tscv.split(X):

        X_train_fold, X_val_fold = X.iloc[train_idx], X.iloc[val_idx]
        y_train_fold, y_val_fold = y.iloc[train_idx], y.iloc[val_idx]

        model = Ridge(**params)
        model.fit(X_train_fold, y_train_fold)

        preds = model.predict(X_val_fold)
        #score = mean_absolute_error(y_val_fold, preds)
        #score = wape(y_val_fold, preds)

        wape_scores.append(wape(y_val_fold, preds))
        mae_scores.append(mean_absolute_error(y_val_fold, preds))
        mse_scores.append(mean_squared_error(y_val_fold, preds))
        rmse_scores.append(np.sqrt(mean_squared_error(y_val_fold, preds)))
        #mape_scores.append(mape(y_val_fold, preds))

    average_metric = np.mean(mae_scores)
    mean_score = mean_metric_scores.append((
                                np.mean(wape_scores), 
                                np.mean(mae_scores), 
                                np.mean(mse_scores), 
                                np.mean(rmse_scores), 
                                0,  # Placeholder for MAPE since it's commented out
                                params
                            ))
    return average_metric

In [62]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best Params:", study.best_params)
print("Best Score:", study.best_value)

[I 2026-04-20 20:05:17,485] A new study created in memory with name: no-name-d7fcf63c-a850-4399-a3d0-e60a699d03fe
[I 2026-04-20 20:05:17,617] Trial 0 finished with value: 7046.57210582799 and parameters: {'alpha': 17.22132046935856}. Best is trial 0 with value: 7046.57210582799.
[I 2026-04-20 20:05:17,744] Trial 1 finished with value: 7036.670263349137 and parameters: {'alpha': 26.100968285537654}. Best is trial 1 with value: 7036.670263349137.
[I 2026-04-20 20:05:17,887] Trial 2 finished with value: 7038.624672193405 and parameters: {'alpha': 24.02914787778521}. Best is trial 1 with value: 7036.670263349137.
[I 2026-04-20 20:05:18,028] Trial 3 finished with value: 7066.5289348481165 and parameters: {'alpha': 6.894337679137302}. Best is trial 1 with value: 7036.670263349137.
[I 2026-04-20 20:05:18,158] Trial 4 finished with value: 7024.375018699368 and parameters: {'alpha': 45.175758977385755}. Best is trial 4 with value: 7024.375018699368.
[I 2026-04-20 20:05:18,289] Trial 5 finished with value: 7035.9634405987845 and parameters: {'alpha': 26.898490446319375}. Best is trial 4 with value: 7024.375018699368.
[I 2026-04-20 20:05:18,418] Trial 6 finished with value: 7030.2679179956895 and parameters: {'alpha': 34.46780127552777}. Best is trial 4 with value: 7024.375018699368.
[I 2026-04-20 20:05:18,543] Trial 7 finished with value: 7038.390741664018 and parameters: {'alpha': 24.266854794211}. Best is trial 4 with value: 7024.375018699368.
[I 2026-04-20 20:05:18,672] Trial 8 finished with value: 7072.436508531743 and parameters: {'alpha': 4.9142368159982155}. Best is trial 4 with value: 7024.375018699368.
[I 2026-04-20 20:05:18,798] Trial 9 finished with value: 7034.779836182902 and parameters: {'alpha': 28.29720004157449}. Best is trial 4 with value: 7024.375018699368.
[I 2026-04-20 20:05:18,931] Trial 10 finished with value: 7022.4306041639 and parameters: {'alpha': 49.62709507171199}. Best is trial 10 with value: 7022.4306041639.
[I 2026-04-20 20:05:19,081] Trial 11 finished with value: 7022.565460955283 and parameters: {'alpha': 49.29964865484785}. Best is trial 10 with value: 7022.4306041639.
[I 2026-04-20 20:05:19,217] Trial 12 finished with value: 7022.291486194093 and parameters: {'alpha': 49.96758009381003}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:19,350] Trial 13 finished with value: 7025.921992945296 and parameters: {'alpha': 42.00000491833401}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:19,483] Trial 14 finished with value: 7028.242506927653 and parameters: {'alpha': 37.749896815531095}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:19,612] Trial 15 finished with value: 7023.2251482988895 and parameters: {'alpha': 47.73908542016239}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:19,740] Trial 16 finished with value: 7026.87074273246 and parameters: {'alpha': 40.194863524839185}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:19,869] Trial 17 finished with value: 7029.542976244156 and parameters: {'alpha': 35.60260277187513}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,001] Trial 18 finished with value: 7050.46176738261 and parameters: {'alpha': 14.608031152370438}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,133] Trial 19 finished with value: 7024.342903927274 and parameters: {'alpha': 45.244825017834074}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,268] Trial 20 finished with value: 7031.853417491134 and parameters: {'alpha': 32.13394382466136}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,396] Trial 21 finished with value: 7022.42414548733 and parameters: {'alpha': 49.64284203800025}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,527] Trial 22 finished with value: 7022.645427523035 and parameters: {'alpha': 49.106769363227464}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,656] Trial 23 finished with value: 7025.49033781116 and parameters: {'alpha': 42.85531444656926}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,785] Trial 24 finished with value: 7024.674435327007 and parameters: {'alpha': 44.53784288684418}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:20,914] Trial 25 finished with value: 7022.378276128705 and parameters: {'alpha': 49.7548417810247}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:21,082] Trial 26 finished with value: 7027.321920834563 and parameters: {'alpha': 39.37023878391735}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:21,310] Trial 27 finished with value: 7032.280841711899 and parameters: {'alpha': 31.53678878536845}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:21,586] Trial 28 finished with value: 7092.130288208933 and parameters: {'alpha': 0.17174055135297905}. Best is trial 12 with value: 7022.291486194093.
[I 2026-04-20 20:05:21,868] Trial 29 finished with value: 7023.768188251196 and parameters: {'alpha': 46.50441627400538}. Best is trial 12 with value: 7022.291486194093.

Best Params: {'alpha': 49.96758009381003}
Best Score: 7022.291486194093

In [63]:
formatted_data = []
for wape, mae, mse, rmse, mape, params in mean_metric_scores:
    # Combine metrics and the params dictionary into one flat dict
    row = {
        'WAPE': wape, 'MAE': mae, 'MSE': mse, 
        'RMSE': rmse, 'MAPE': mape
    }
    row.update(params)
    formatted_data.append(row)

df = pd.DataFrame(formatted_data)
df

        WAPE          MAE           MSE         RMSE  MAPE      alpha
0   0.164561  7046.572106  1.001582e+08  9931.404415     0  17.221320
1   0.164321  7036.670263  1.000472e+08  9924.960239     0  26.100968
2   0.164369  7038.624672  1.000691e+08  9926.237594     0  24.029148
3   0.165040  7066.528935  1.003855e+08  9944.342360     0   6.894338
4   0.164022  7024.375019  9.990895e+07  9916.846825     0  45.175759
5   0.164304  7035.963441  1.000392e+08  9924.497402     0  26.898490
6   0.164166  7030.267918  9.997520e+07  9920.747823     0  34.467801
7   0.164363  7038.390742  1.000665e+08  9926.085204     0  24.266855
8   0.165180  7072.436509  1.004539e+08  9948.166257     0   4.914237
9   0.164275  7034.779836  1.000259e+08  9923.720915     0  28.297200
10  0.163974  7022.430604  9.988702e+07  9915.551648     0  49.627095
11  0.163978  7022.565461  9.988855e+07  9915.641773     0  49.299649
12  0.163971  7022.291486  9.988545e+07  9915.458742     0  49.967580
13  0.164060  7025.921993  9.992636e+07  9917.873948     0  42.000005
14  0.164116  7028.242507  9.995245e+07  9919.410180     0  37.749897
15  0.163994  7023.225148  9.989600e+07  9916.082116     0  47.739085
16  0.164083  7026.870743  9.993702e+07  9918.501973     0  40.194864
17  0.164148  7029.542976  9.996705e+07  9920.268703     0  35.602603
18  0.164655  7050.461767  1.002020e+08  9933.922598     0  14.608031
19  0.164021  7024.342904  9.990859e+07  9916.825505     0  45.244825
20  0.164204  7031.853417  9.999304e+07  9921.794362     0  32.133944
21  0.163974  7022.424145  9.988695e+07  9915.547333     0  49.642842
22  0.163980  7022.645428  9.988945e+07  9915.695222     0  49.106769
23  0.164049  7025.490338  9.992151e+07  9917.587972     0  42.855314
24  0.164029  7024.674435  9.991232e+07  9917.045717     0  44.537843
25  0.163973  7022.378276  9.988643e+07  9915.516694     0  49.754842
26  0.164094  7027.321921  9.994209e+07  9918.800558     0  39.370239
27  0.164215  7032.280842  9.999785e+07  9922.076407     0  31.536789
28  0.165645  7092.130288  1.006883e+08  9961.067837     0   0.171741
29  0.164007  7023.768188  9.990212e+07  9916.443757     0  46.504416

In [64]:
df.to_csv('ridge_errorfile_sales.csv', header=True, index=False)

In [65]:
study.best_params

{'alpha': 49.96758009381003}